accounts/urls.py
# myblog/accounts/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

blogparts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),# defaults@staff_member_required
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# accountapp/blogs/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'blogs'

urlpatterns = [
    # ex: /
    path('', views.IndexView.as_view(), name='index'),
    # ex: /blogs/create/
    path('create/', views.CreateView.as_view(), name='create'),
    # ex: /blogs/1/
    path('editlist/', views.EditListView.as_view(), name='editlist'),

    path('<int:pk>/', views.PostDetailFormView.as_view(), name='detail'),
    # ex: /blogs/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # ex: /blogs/ajax/1/update/ for ajax asynchronized post
    path('<int:pk>/update/ajax', views.PostUpdateView.as_view(), name='update-ajax'),
    # asynchronized image, tag, caegory, series
    path('<int:pk>/update/ajax/image/', views.PostImageView.as_view(), name='update-ajax-image'),
    path('ajax/add_tags/', views.AddTagView.as_view(), name='add-tag'),
    path('ajax/add-category/', views.AddCategoryView.as_view(), name='add-category'),
    path('ajax/add_series/', views.AddSeriesView.as_view(), name='add-series'),
    path('ajax/add_pictures/', views.AddPicturesView.as_view(), name='add-pictures'),

    # ex: /blogs/1/delete
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),

]

home/urls.py
# mysite/home/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'home'

urlpatterns = [
    # ex: /
    path('', views.HomeView.as_view(), name='home'),
]

blogs/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.urls import reverse
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import strip_tags
import os
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from django.db.models import signals
from django.core.mail import send_mail
from django.template import loader


class Category(models.Model):
    name = models.CharField('Category', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(category__parent=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def public_counter(self):
        count = self.post_set.filter(is_public=True).count()
        return count

    def get_absolute_url(self):
        return reverse('blogs:index')

class Tag(models.Model):
    name = models.CharField('Tag', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(tag=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def get_absolute_url(self):
        return reverse('blogs:index')

class Series(models.Model):
    name = models.CharField('Series', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(series__parent=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def public_counter(self):
        count = self.post_set.filter(is_public=True).count()
        return count

    def get_absolute_url(self):
        return reverse('blogs:index')

class Pictures(models.Model):
    image = ProcessedImageField(
        upload_to="uploads/%Y/%m/%d/",
        null=False,
        blank=False,
        processors=[ResizeToFill(830, 580)], format="JPEG", options={'quality': 90},
        verbose_name="Picture"
    )
    thumbnail = ProcessedImageField(
        upload_to="",
        null=True,
        blank=True,
        processors=[ResizeToFill(75, 75)], format="JPEG", options={'quality': 90},
    )

    def save(self, *args, **kwargs):
        super(Pictures, self).save(*args, **kwargs)
        if not self.make_thumbnail():
            # set to a default thumbnail
            raise Exception('Could not create thumbnail - is the file type valid?')

    def make_thumbnail(self):
        image = Image.open(self.image)
        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        # thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + '_thumb' + thumb_extension
        temp_thumb = BytesIO()
        image.save(temp_thumb, 'JPEG') #file objectをstring形式として、contentfileに保存
        temp_thumb.seek(0) #You need to seek back to the beginning of the file after writing the initial in memory file...
        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        return True

    def __str__(self):
        return self.image.name

    def get_absolute_url(self):
        return reverse('blogs:index')

class Post(models.Model):
    title = models.CharField("Title", max_length=255, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, verbose_name="Author",
        blank=True, null=True,
    )
    image = ProcessedImageField(
        upload_to="blogs/post_img/%y/%m/%d/",
        null=True,
        blank=True,
        processors=[ResizeToFill(830, 580)], format="JPEG", options={'quality': 90},
        verbose_name="Featured image"
    )
    series = models.ForeignKey(Series, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Series")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Category")
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="Tags")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    body = RichTextUploadingField("Body", blank=True, null=True,)
    is_public = models.BooleanField('公開設定', default=False,)
    notification = models.BooleanField('通知設定', default=False,)

    def __str__(self):
        return self.title

    def summary(self):
        return strip_tags(self.body)[:30]

    def long_summary(self):
        return strip_tags(self.body)[:150]

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True, null=True,
    )
    created_at = models.DateTimeField('投稿日',auto_now_add=True)
    body = models.TextField('本文', max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.author


def notify_admin(sender, instance, created, **kwargs):
    '''Notify the administrator that a new post has been added.'''
    if instance.notification:
        if settings.EMAIL_BY and settings.EMAIL_TO:
            subject = 'New post from %s !!!' % instance.author
            mail_template = loader.get_template('blogs/post-notification.txt')
            context = {
                "post": instance,
            }
            message = mail_template.render(context)
            from_addr = settings.EMAIL_BY
            recipient_list = settings.EMAIL_TO
            send_mail(subject, message, from_addr, recipient_list)

signals.post_save.connect(notify_admin, sender=Post)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin

from blogs.models import Post, Comment, Category, Tag, Series
from webmapping.models import Marker

class HomeView(LoginRequiredMixin, generic.base.TemplateView):
    template_name = "home/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_posts'] = Post.objects.filter(is_public=True).order_by('-updated_at')[:4]
        context["marker_lists"] = Marker.objects.all()
        return context

home/templates/home/home.html
{% load i18n static %}
{% load leaflet_tags %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Beeeee Blog</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="all,follow">

<link rel="stylesheet" href="{% static 'blogs/vendor/bootstrap/css/bootstrap.min.css' %}">
<!-- Font Awesome CSS-->
<link rel="stylesheet" href="{% static 'blogs/vendor/font-awesome/css/font-awesome.min.css' %}">
<!-- Custom icon font-->
<link rel="stylesheet" href="{% static 'blogs/css/fontastic.css' %}">
<!-- Google fonts - Open Sans-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<!-- Fancybox-->
<link rel="stylesheet" href="{% static 'blogs/vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
<!-- theme stylesheet-->
<!-- <link rel="stylesheet" href="{% static 'blogs/css/style.default.css' %}" id="theme-stylesheet"> -->
<link rel="stylesheet" href="{% static 'blogs/css/style.sea.css' %}" id="theme-stylesheet">
<!-- Custom stylesheet - for your changes-->
<link rel="stylesheet" href="{% static 'blogs/css/custom.css' %}">
{% block extra_css %}{% endblock %}
    <!-- Favicon-->
    <!-- <link rel="shortcut icon" href="favicon.png"> -->
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body class="home">
    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <!-- Search Box -->
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" placeholder="検索">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="{% url 'home:home' %}" class="navbar-brand">Beeeee Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="{% url 'home:home' %}" class="nav-link ">Home</a>
              </li>
              <li class="nav-item"><a href="{% url 'blogs:index' %}" class="nav-link ">Blog</a>
              </li>
              <li class="nav-item"><a href="{% url 'blogs:create' %}" class="nav-link active ">Post</a>
              </li>
              <!-- <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
              </li> -->
              {% if user.is_authenticated %}
              <!-- <li class="nav-item"><a href="#" class="nav-link ">Profile</a>
              </li> -->
              <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
              {% else %}
              <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="nav-link">Sign up</a></li>
              <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
              {% endif %}
            </ul>
            <!-- <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul> -->
          </div>
        </div>
      </nav>
    </header>

    <!-- Hero Section-->
    <section style="background: url({% static 'home/img/hero-demo.jpg' %}); background-size: cover; background-position: center center" class="hero">
      <div class="container">
        <div class="row">
          <div class="col-lg-7">
            <h1>Beeeee Blog</br>    - Shared Diary -</h1><a href="{% url  'blogs:index' %}" class="hero-link">Check messages</a>
          </div>
        </div><a href=".intro" class="continue link-scroll"><i class="fa fa-long-arrow-down"></i> Scroll Down</a>
      </div>
    </section>
    <!-- Intro Section-->
    <section class="intro">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h2 class="h3">Let's Share A Diary!</h2>
            <p class="text-big">Here is intro space.</p>
            <p class="text-big"><strong>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</strong> </p>
          </div>
        </div>
      </div>
    </section>
    <section class="featured-posts no-padding-top">
      <div class="container">
        <!-- Post-->
        {%for post in latest_posts %}
        <div class="row d-flex align-items-stretch">
        {% if forloop.counter|divisibleby:2%}
          {% if post.image %}
            <a href="{% url 'blogs:detail' post.id %}" class="image col-lg-5">
            <img src="{{post.image.url}}" alt="..."></a>
          {% else %}
            <a href="{% url 'blogs:detail' post.id %}" class="image col-lg-5">
            <img src="{% static 'blogs/img/post-img-temp-cat.svg' %}" alt="..." ></a>
          {% endif %}
        {% endif %}
          <div class="text col-lg-7">
            <div class="text-inner d-flex align-items-center">
              <div class="content">
                <header class="post-header">
                  <div class="category">{{post.category}}</div><a href="{% url 'blogs:detail' post.id %}">
                    <h2 class="h4">{{post.title}}</h2></a>
                </header>
                  <p>{{post.long_summary}}</p>
                <footer class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{post.author.avatar.url}}" alt="..." class="img-fluid"></div>
                    <div class="title"><span>{{post.author}}</span></div></a>
                  <div class="date"><i class="icon-clock"></i>{{post.updated_at|timesince}}前</div>
                  <div class="comments"><i class="icon-comment"></i>{{post.comment_set.count}}</div>
                </footer>
              </div>
            </div>
          </div>
        {% if not forloop.counter|divisibleby:2 %}
          {% if post.image %}
            <a href="{% url 'blogs:detail' post.id %}" class="image col-lg-5">
            <img src="{{post.image.url}}" alt="..."></a>
          {% else %}
            <a href="{% url 'blogs:detail' post.id %}" class="image col-lg-5">
            <img src="{% static 'blogs/img/post-img-temp-cat.svg' %}" alt="..." ></a>
          {% endif %}
        {% endif %}
        </div>
        {% endfor %}
      </div>
    </section>

    <!-- Divider Section-->
    <section style="background: url({% static 'home/img/divider.jpg' %}); background-size: cover; background-position: center bottom" class="divider">
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</h2><a href="#" class="hero-link">View More</a>
          </div>
        </div>
      </div>
    </section>

    <section class="maps">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <h2>where we visited</h2>
            <p class="text-big">we have went thousands places and made precious memories that we cannot forget. Here is a marked world map where we visited. enjoy our memories travel.</p>
          </div>
        </div>
      </div>
      <div class="leaflet">
        {% leaflet_map "yourmap" callback="window.map_init_basic" %}
      </div>
    </section>

    <!-- Page Footer-->
    <footer class="main-footer">
      <div class="copyrights custom-copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 17 Apr. 2017. All rights reserved. Beeeeeblog.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>Template By <a href="https://bootstraptemple.com" class="text-white">Bootstrap Temple</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Javascript files-->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"> </script>
    <script src="{% static 'blogs/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blogs/vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
    <script src="{% static 'blogs/vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'blogs/js/front.js' %}"></script>
    <script type="text/javascript">
      function map_init_basic (map, options) {
        var icon_base = L.Icon.extend({
        options: {
          iconSize: [50, 50],
          iconAnchor: [-16, 70],
          popupAnchor: [0, -10],
          shadowUrl: "{% static 'webmapping/fukidashi.png' %}",
          shadowSize:   [80, 80],
          shadowAnchor: [0, 80],
        }});
        map.scrollWheelZoom.disable();
      {% for list in marker_lists %}
        var myicon = new icon_base({
          iconUrl: "{{list.thumbnail.url}}",
          iconRetinaUrl: "{{list.thumbnail.url}}"
        });
        var comment = '<div><img src="{{list.image.url}}" width="200px"><p>{{list.name}}</p></div>';
        L.marker([{{list.latitude}},{{list.longitude}}], { icon: myicon }).bindPopup(comment).addTo(map);
      {% endfor %}
        }
    </script>
    {% block extra_js %}{% endblock %}
    {% leaflet_js  plugins="bouncemarker,draw" %}
    {% leaflet_css plugins="bouncemarker,draw" %}
  </body>
</html>