blogparts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),# defaults@staff_member_required
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# accountapp/blogs/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'blogs'

urlpatterns = [
    # ex: /
    path('', views.IndexView.as_view(), name='index'),
    # ex: /blogs/create/
    path('create/', views.CreateView.as_view(), name='create'),
    # ex: /blogs/1/
    path('editlist/', views.EditListView.as_view(), name='editlist'),

    path('<int:pk>/', views.PostDetailFormView.as_view(), name='detail'),
    # ex: /blogs/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # ex: /blogs/ajax/1/update/ for ajax asynchronized post
    path('<int:pk>/update/ajax', views.PostUpdateView.as_view(), name='update-ajax'),
    # asynchronized image, tag, caegory, series
    path('<int:pk>/update/ajax/image/', views.PostImageView.as_view(), name='update-ajax-image'),
    path('ajax/add_tags/', views.AddTagView.as_view(), name='add-tag'),
    path('ajax/add-category/', views.AddCategoryView.as_view(), name='add-category'),
    path('ajax/add_series/', views.AddSeriesView.as_view(), name='add-series'),
    path('ajax/add_pictures/', views.AddPicturesView.as_view(), name='add-pictures'),

    # ex: /blogs/1/delete
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),

]

home/urls.py
# mysite/home/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'home'

urlpatterns = [
    # ex: /
    path('', views.HomeView.as_view(), name='home'),
]

blogs/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.urls import reverse
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils.html import strip_tags
import os
from PIL import Image
from io import BytesIO
from django.core.files.base import ContentFile
from django.db.models import signals
from django.core.mail import send_mail
from django.template import loader


class Category(models.Model):
    name = models.CharField('Category', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(category__parent=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def public_counter(self):
        count = self.post_set.filter(is_public=True).count()
        return count

    def get_absolute_url(self):
        return reverse('blogs:index')

class Tag(models.Model):
    name = models.CharField('Tag', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(tag=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def get_absolute_url(self):
        return reverse('blogs:index')

class Series(models.Model):
    name = models.CharField('Series', max_length=255)
    created_at = models.DateTimeField('created time', auto_now_add=True)

    def __str__(self):
        return self.name

    def get_latest_post(self):
        result = Post.objects.filter(series__parent=self).filter(is_public=True).order_by('-created_at')[:5]
        return result

    def public_counter(self):
        count = self.post_set.filter(is_public=True).count()
        return count

    def get_absolute_url(self):
        return reverse('blogs:index')

class Pictures(models.Model):
    image = ProcessedImageField(
        upload_to="uploads/%Y/%m/%d/",
        null=False,
        blank=False,
        processors=[ResizeToFill(830, 580)], format="JPEG", options={'quality': 90},
        verbose_name="Picture"
    )
    thumbnail = ProcessedImageField(
        upload_to="",
        null=True,
        blank=True,
        processors=[ResizeToFill(75, 75)], format="JPEG", options={'quality': 90},
    )

    def save(self, *args, **kwargs):
        super(Pictures, self).save(*args, **kwargs)
        if not self.make_thumbnail():
            # set to a default thumbnail
            raise Exception('Could not create thumbnail - is the file type valid?')

    def make_thumbnail(self):
        image = Image.open(self.image)
        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        # thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + '_thumb' + thumb_extension
        temp_thumb = BytesIO()
        image.save(temp_thumb, 'JPEG') #file objectをstring形式として、contentfileに保存
        temp_thumb.seek(0) #You need to seek back to the beginning of the file after writing the initial in memory file...
        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        return True

    def __str__(self):
        return self.image.name

    def get_absolute_url(self):
        return reverse('blogs:index')

class Post(models.Model):
    title = models.CharField("Title", max_length=255, blank=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, verbose_name="Author",
        blank=True, null=True,
    )
    image = ProcessedImageField(
        upload_to="blogs/post_img/%y/%m/%d/",
        null=True,
        blank=True,
        processors=[ResizeToFill(830, 580)], format="JPEG", options={'quality': 90},
        verbose_name="Featured image"
    )
    series = models.ForeignKey(Series, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Series")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Category")
    tag = models.ManyToManyField(Tag, blank=True, verbose_name="Tags")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    body = RichTextUploadingField("Body", blank=True, null=True,)
    is_public = models.BooleanField('公開設定', default=False,)
    notification = models.BooleanField('通知設定', default=False,)

    def __str__(self):
        return self.title

    def summary(self):
        return strip_tags(self.body)[:30]

    def long_summary(self):
        return strip_tags(self.body)[:150]

    def get_absolute_url(self):
        return reverse('blogs:detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        blank=True, null=True,
    )
    created_at = models.DateTimeField('投稿日',auto_now_add=True)
    body = models.TextField('本文', max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.author


def notify_admin(sender, instance, created, **kwargs):
    '''Notify the administrator that a new post has been added.'''
    if instance.notification:
        if settings.EMAIL_BY and settings.EMAIL_TO:
            subject = 'New post from %s !!!' % instance.author
            mail_template = loader.get_template('blogs/post-notification.txt')
            context = {
                "post": instance,
            }
            message = mail_template.render(context)
            from_addr = settings.EMAIL_BY
            recipient_list = settings.EMAIL_TO
            send_mail(subject, message, from_addr, recipient_list)

signals.post_save.connect(notify_admin, sender=Post)

blogs/forms.py
from django import forms
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from .models import Comment, Post, Category, Tag, Series, Pictures

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("author", "body")

class SearchForm(forms.ModelForm):
    word = forms.CharField(max_length=10)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ( "title", "image", "series", "category", "tag", "body","is_public", "notification",)

class PostImageForm(forms.ModelForm):
    # body = forms.CharField(widget=CKEditorUploadingWidget())
    class Meta:
        model = Post
        fields = ( "image",)

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name",)

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ("name",)

class SeriesForm(forms.ModelForm):
    class Meta:
        model = Series
        fields = ("name",)

class PicturesForm(forms.ModelForm):
    class Meta:
        model = Pictures
        fields = ("image",)

blogs/views.py
from django.shortcuts import render

# Create your views here.
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.views import generic
from django.views.generic.edit import FormMixin
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Post, Comment, Category, Tag, Series
from .forms import CommentForm, CategoryForm, SeriesForm, TagForm, PostForm, PostImageForm, PicturesForm

from blogs import utils as blogs_utils

class IndexView(LoginRequiredMixin, generic.ListView):
    model = Post
    paginate_by = 6
    ordering = ['-updated_at']
    context_object_name = "object_list"

    def get_queryset(self):
        obj_list = Post.objects.all()

        if self.request.GET.get('category'):
            filtered = self.request.GET.get('category')
            obj_list = obj_list.filter(category__name=filtered)
        if self.request.GET.get('tag'):
            filtered = self.request.GET.get('tag')
            obj_list = obj_list.filter(tag__name=filtered)

        return obj_list.filter(is_public=True).order_by('-updated_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = blogs_utils.get_category_all()
        tags = blogs_utils.get_tag_all()
        context["categories"] = categories
        context["tags"] = tags
        return context


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):  # The LoginRequired mixin
    model = Post
    success_url = reverse_lazy('blogs:index')
    template_name = 'blogs/post_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        # ownership validation
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to delete.')

        return super(DeleteView, self).dispatch(request, *args, **kwargs)

class EditListView(LoginRequiredMixin, generic.ListView):
    model = Post
    paginate_by = 25
    template_name = 'blogs/post_editlist.html'

    def get_queryset(self):
        obj_list = Post.objects.all()
        user = self.request.user
        obj_list = obj_list.filter(author=user)
        return obj_list.order_by('-created_at')


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post_pk = self.kwargs['pk']
        post_list = Post.objects.all().filter(is_public=True)
        current = Post.objects.get(pk=post_pk)

        if current.series:#Series化されている場合はそちらでpaginate
            post_list = post_list.filter(series__name=current.series)
        try:
            context["prev_obj"] = post_list.filter(pk__lt=post_pk).order_by('-pk').first()
        except IndexError:
            context["prev_obj"] = False
        try:
            context["next_obj"] = post_list.filter(pk__gt=post_pk).order_by('pk').first()
        except IndexError:
            context["next_obj"] = False

        categories = blogs_utils.get_category_all()
        tags = blogs_utils.get_tag_all()
        context["categories"] = categories
        context["tags"] = tags

        return context

class PostDetailFormView(LoginRequiredMixin, FormMixin, DetailView):#classでも使える
    model = Post # shorthand for setting queryset = Post.objects.all()
    template_name = "blogs/post_detail.html"
    context_object_name = "post"
    form_class = CommentForm

    def post(self, request, *args, **kwargs):#有効か否かチェックする
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):#foreignkeyのひもづけ
        post_pk = self.kwargs['pk']
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.post = Post.objects.get(pk=post_pk)
        self.object.save()
        return redirect('blogs:detail', pk=post_pk)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def dispatch(self, request, *args, **kwargs):
        # ownership validation
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission.')

        return super().dispatch(request, *args, **kwargs)

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Post
    fields = []
    template_name = 'blogs/post_create.html'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):# make autherized post
        post = Post.objects.create(author=self.request.user, is_public=False)
        return_url = reverse('blogs:update',args=[post.id,])
        return HttpResponseRedirect(return_url)

class AjaxMixin(LoginRequiredMixin):  # to be available at ajax
    ajax = None

    def __init__(self, **kwargs):
        self.ajax = kwargs.get('ajax',None)
        super(AjaxMixin, self).__init__()

    def dispatch(self, request, *args, **kwargs):
        # ownership validation
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('You do not have permission to edit.')
        return super(AjaxMixin, self).dispatch(request, *args, **kwargs)

    def form_invalid(self, form):
        if self.ajax:
            response = super(AjaxMixin, self).form_invalid(form)
            if self.request.is_ajax():
                return JsonResponse(form.errors, status=400)
            else:
                return response
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_valid(self, form):
        self.object = form.save()
        if self.ajax:
            response = super(AjaxMixin, self).form_valid(form)
            if self.request.is_ajax():
                data = {
                "comment": "Success!",
                }
                return JsonResponse(data)
            else:
                return response
        else:
            return redirect('blogs:index')

class PostUpdateView(generic.edit.UpdateView, AjaxMixin):
    model = Post
    ajax = True
    template_name = 'blogs/post_update.html'
    form_class = PostForm
    success_url = reverse_lazy('blogs:index')

class PostImageView(generic.edit.UpdateView, AjaxMixin): #save image asyncronizingly
    model = Post
    ajax = True
    form_class = PostImageForm
    template_name = 'blogs/post_update.html'

    def form_valid(self,form):
        super().form_valid(form)
        if self.request.is_ajax():
            data = {
            # "output_url": self.object.image.url(),
            }
            return JsonResponse(data)

class AddCategoryView(generic.edit.CreateView, AjaxMixin): # The LoginRequired mixin
    model = Category
    ajax = True
    form_class = CategoryForm
    template_name = 'blogs/post_add.html'

class AddSeriesView(generic.edit.CreateView, AjaxMixin): # The LoginRequired mixin
    model = Series
    ajax = True
    form_class = SeriesForm
    template_name = 'blogs/post_add.html'

class AddTagView(generic.edit.CreateView, AjaxMixin): # The LoginRequired mixin
    model = Tag
    ajax = True
    form_class = TagForm
    template_name = 'blogs/post_add.html'

class AddPicturesView(generic.edit.CreateView, AjaxMixin): # The LoginRequired mixin
    model = Tag
    ajax = True
    form_class = PicturesForm
    template_name = 'blogs/post_add.html'

    # def form_valid(self,form):
    #     super().form_valid(form)
    #     if self.request.is_ajax():
    #         data = {
    #         # "output_url": self.object.image.url(),
    #         }
    #         return JsonResponse(data)

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block body %}
<!-- {% for post in posts.all %} -->
  <!-- {% if post.is_public %} -->
    <!-- <a href="{% url 'post-detail' post.id %}"> -->
    <!-- <div class="recent"> -->
      <!-- <img src="{{post.image.thumbnail.url}}" width=300px alt=""> -->
      <!-- <p>{{post.title}}</p> -->
      <!-- <p>{{post.created_at}}</p> -->
      <!-- <p>{{post.summary}}</p> -->
    <!-- </div> -->
    <!-- </a> -->
  <!-- {% else %} -->
  <!-- {% endif %} -->
<!-- {% endfor %} -->
<p>{{test}}</p>
<p>{{result}}</p>
  <a href="./">戻る</a>
{% endblock %}

blogs/templates/blogs/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock %}

{% block body %}
<div class="post-single">
    <div class="login-header">
      <h1>Delete Post</h1>
    </div>
    <section class="common-form">
      <p>Are you sure you want to delete "{{ object.title }}" ?</p>
      <div class="form-group button col-md-12">
        <ul class="boxcontainer">
          <li><form action="" method="post">{% csrf_token %}
              <button type="submit" class="btn btn-secondary delete">Delete</button>
          </form></li>
          <li><p><a class="btn btn-secondary" href="javascript:history.back()">&lt; Back</a></p></li>
        </ul>
    </section>
</div>
{% endblock %}

blogs/templates/blogs/post_create.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}Write Post{% endblock %}

{% block body %}
{# https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#yesno #}
<div class="post-single">
  <div class="login-header">
    <h1>Post</h1>
  </div>
  <section class="common-form">
    <h2>Why not write?</h2>
      <form action="" method="post">
         <div class="row">
          {% csrf_token %}
          <div class="form-group col-md-12">
          </div>
            <ul class="form-group button boxcontainer col-md-12">
              <li><button type="submit" class="btn btn-secondary">New</button></li>
              <li><a href="{% url 'blogs:editlist' %}" class="btn btn-secondary ">Edit</a></li>
          </div>
      </form>
  </section>
</div>
{% endblock %}

blogs/templates/blogs/post_update.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{{ object|yesno:'Edit,Add New'}} Post{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blogs/css/loading.css' %}">
<link rel="stylesheet" href="{% static 'blogs/css/loading-btn.css' %}">
{% endblock %}

{% block body %}
{# https://docs.djangoproject.com/en/2.0/ref/templates/builtins/#yesno #}
<div class="post-single">
  <div class="login-header">
    <h1>Write Post</h1>
  </div>
  <section class="common-form">
    <h2>Why not write daily diary?</h2>
    <div class="container">
     <p><label for="">Add:</label></p>
      <ul class="button boxcontainer">
        <li><a href="#modal-series" class="btn btn-secondary go">Series</a></li>
        <li><a href="#modal-category" class="btn btn-secondary go">Category</a></li>
        <li><a href="#modal-tag" class="btn btn-secondary go">Tag</a></li>
        <li><a href="#modal-pictures" class="btn btn-secondary go">Picture</a></li>
      </ul>
   </div>
      <form action="" method="post" enctype="multipart/form-data">
         <div class="row">
          {% csrf_token %}
          <div class="form-group col-md-12">
            {{ form.as_p }}
          </div>
          <div class="form-group button col-md-12">
            <ul class="boxcontainer">
              <li> <a href="{% url 'blogs:delete' post.pk %}" class="btn btn-secondary delete">Delete</a></li>
              <li><a href="{% url 'blogs:index' %}" class="btn btn-secondary ">Cancel</a></li>
              <li><button type="submit" class="btn btn-secondary">Save</button></li>
            </ul>
          </div>
          </div>
      </form>
<!-- alert -->
      <div class="alert alert-success fixed-top" id="success-alert" style="display:none"> Auto Saved...</div>
<!-- endalert -->

<!-- series form -->
       	<div id="modal-series" class="modal-frame">
          <div class="overlay">
            <div class="modal-contents">
       				<a href="#" class="close-button">&times;</a>
              <form class=""  method="post">
                  {% csrf_token %}
                  <p><label for="id_add_series">Series name:</label> <input type="text" name="add_series" maxlength="255" id="id_add_series" /></p>
                  <button type="submit" id="id_add_series_submit" class="btn btn-secondary ld-over add_series_submit">Submit<div class="ld ld-ball ld-bounce"></div></button>
              </form>
       		   </div>
          </div>
       	</div>
<!-- category form -->
        <div id="modal-category" class="modal-frame">
          <div class="overlay">
            <div class="modal-contents">
       				<a href="#" class="close-button">&times;</a>
              <form class=""  method="post">
                  {% csrf_token %}
                  <p><label for="id_add_category">Category name:</label> <input type="text" name="add_category" maxlength="255" id="id_add_category" /></p>
                  <button type="submit" id="id_add_category_submit" class="btn btn-secondary ld-over add_category_submit">Submit<div class="ld ld-ball ld-bounce"></div></button>
              </form>
            </div>
          </div>
       	</div>
<!-- tag form -->
        <div id="modal-tag" class="modal-frame">
          <div class="overlay">
            <div class="modal-contents">
       				<a href="#" class="close-button">&times;</a>
              <form class="" id="add_tag_form" method="post">
                  {% csrf_token %}
                  <p><label for="id_add_tag">Tag name:</label> <input type="text" name="add_tag" maxlength="255" id="id_add_tag" /></p>
                  <button type="submit" id="id_add_tag_submit" class="btn btn-secondary ld-over add_tag_submit">Submit<div class="ld ld-ball ld-bounce"></div></button>
              </form>
         		</div>
          </div>
        </div>
<!-- Pictures form -->
        <div id="modal-pictures" class="modal-frame">
          <div class="overlay">
            <div class="modal-contents">
       				<a href="#" class="close-button">&times;</a>
              <form class="" id="add_pictures_form"  method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <p><label for="id_add_pictures">Pictures name:</label> <input type="file" name="add_pictures" id="id_add_pictures" accept="image/*" /></p>
                  <button type="submit" id="id_add_pictures_submit" class="btn btn-secondary ld-over add_pictures_submit">Submit<div class="ld ld-ball ld-bounce"></div></button>
              </form>
         		</div>
          </div>
        </div>
  </section>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<!-- <script type="text/javascript" src="{% static "blogs/js/addajax.js" %}"></script> -->

<script>
$(function() {
  function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
  }
  var csrftoken = getCookie('csrftoken');

  function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
      beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
              xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
      }
  });

  var add = function (e) {
  var thisform = this;
  var formData = new FormData();
  var form = e.data.form;
  var loading = e.data.loading;
  var targetpath = e.data.targetpath;
  var cacheflag = e.data.cache;
  if (cacheflag) {
    formData.append('image', $(form)[0].files[0]);
  } else {
    formData.append('name', $(form).val());
  }
  $.ajax({
  url: targetpath,
  datatype: 'json',
  cache: cacheflag,
  type: 'post',
  data:formData,
  processData: false,
  contentType: false,
  beforeSend: function(xhr, settings) {
    $(loading).addClass("running");
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
      };
  },
  success:console.log(formData), // 送信に成功したとき
  success:function(){
    $(loading).removeClass("running");
    $(thisform).after('<p class="submitted">Successfully submitted</p>');
  },
  }).done(function(response){
    console.log('success!');  // レスポンスがあったとき
    $(loading).removeClass("running");
  }).fail(function(jqXHR, textStatus, errorThrown) {
    console.log("エラーが発生しました。ステータス：" + jqXHR.status); // エラーが発生したとき
    $(loading).removeClass("running");
    $(thisform).after('<p class="submitted">Failed to submit...</p>');
  });
  return false;
  };

  $("#id_add_tag_submit").click({
    loading : ".add_tag_submit",
    form : "#id_add_tag",
    targetpath : '{% url "blogs:add-tag" %}',
    cache : false,
  },
  add
  );

  $("#id_add_category_submit").click({
    loading : ".add_category_submit",
    form : "#id_add_category",
    targetpath : '{% url "blogs:add-category" %}',
    cache : false,
  },
  add
  );

  $("#id_add_series_submit").click({
    loading : ".add_series_submit",
    form : "#id_add_series",
    targetpath : '{% url "blogs:add-series" %}',
    cache : false,
  },
  add
  );

  $("#id_add_pictures_submit").click({
    loading : ".add_pictures_submit",
    form : "#id_add_pictures",
    targetpath : '{% url "blogs:add-pictures" %}',
    cache : true,
  },
  add);

  $('#id_image').on('change', function() {
  var formData = new FormData();
  var targetpath = '{% url "blogs:update-ajax-image" post.id %}';
  formData.append('image', $(this)[0].files[0]);
  $.ajax({
  url: targetpath,
  type: 'post',
  dataType: 'json',
  data: formData,
  processData: false,
  contentType: false,
  success:console.log('send featured image!'), // 送信に成功したとき
  }).done(function(response){
    console.log('success!');  // レスポンスがあったとき
  }).fail(function(jqXHR, textStatus, errorThrown) {
    console.log("エラーが発生しました。ステータス：" + jqXHR.status); // エラーが発生したとき
  });
  return false;
  });

  setInterval(function() {
  $.ajax({
  url: '{% url "blogs:update-ajax" post.id %}',
  datatype: 'json',
  cache: false,
  type: 'post',
  data:{
    "title": $("#id_title").val(),
    "image": $("#id_image").val(),
    "series": $("#id_series").val(),
    "category": $("#id_category").val(),
    "tag": $("#id_tag").val(),
    "body": CKEDITOR.instances.id_body.getData(),
    "is_public": $("#id_is_public:checked").val(),
    "notification": "",
  },
  success:function(){
  $("#success-alert").show();
  setTimeout(function() { $("#success-alert").hide(); }, 2000);
  },
  success:console.log('send auto-save data!'), // 送信に成功したとき
  }).done(function(response){
  console.log('success!');  // レスポンスがあったとき
  }).fail(function(jqXHR, textStatus, errorThrown) {
  console.log("エラーが発生しました。ステータス：" + jqXHR.status); // エラーが発生したとき
  });
  },
  90000
  );
})
</script>
{% endblock %}