blogparts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blogs/', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),# defaults@staff_member_required
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# accountapp/blogs/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'blogs'

urlpatterns = [
    # ex: /
    path('', views.IndexView.as_view(), name='index'),
    # ex: /blogs/create/
    path('create/', views.CreateView.as_view(), name='create'),
    # ex: /blogs/1/
    path('editlist/', views.EditListView.as_view(), name='editlist'),

    path('<int:pk>/', views.PostDetailFormView.as_view(), name='detail'),
    # ex: /blogs/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    # ex: /blogs/ajax/1/update/ for ajax asynchronized post
    path('<int:pk>/update/ajax', views.PostUpdateView.as_view(), name='update-ajax'),
    # asynchronized image, tag, caegory, series
    path('<int:pk>/update/ajax/image/', views.PostImageView.as_view(), name='update-ajax-image'),
    path('ajax/add_tags/', views.AddTagView.as_view(), name='add-tag'),
    path('ajax/add-category/', views.AddCategoryView.as_view(), name='add-category'),
    path('ajax/add_series/', views.AddSeriesView.as_view(), name='add-series'),
    path('ajax/add_pictures/', views.AddPicturesView.as_view(), name='add-pictures'),

    # ex: /blogs/1/delete
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),

]

home/urls.py
# mysite/home/urls.py

from django.urls import path, include

from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/
app_name = 'home'

urlpatterns = [
    # ex: /
    path('', views.HomeView.as_view(), name='home'),
]

templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %} - Beeeee Blog -</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="all,follow">

<link rel="stylesheet" href="{% static 'blogs/vendor/bootstrap/css/bootstrap.min.css' %}">
<!-- Font Awesome CSS-->
<link rel="stylesheet" href="{% static 'blogs/vendor/font-awesome/css/font-awesome.min.css' %}">
<!-- Custom icon font-->
<link rel="stylesheet" href="{% static 'blogs/css/fontastic.css' %}">
<!-- Google fonts - Open Sans-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
<!-- Fancybox-->
<link rel="stylesheet" href="{% static 'blogs/vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
<!-- theme stylesheet-->
<!-- <link rel="stylesheet" href="{% static 'blogs/css/style.default.css' %}" id="theme-stylesheet"> -->
<link rel="stylesheet" href="{% static 'blogs/css/style.sea.css' %}" id="theme-stylesheet">
<!-- Custom stylesheet - for your changes-->
<link rel="stylesheet" href="{% static 'blogs/css/custom.css' %}">
<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}" rel="stylesheet">
{% block extra_css %}{% endblock %}
</head>

<body>
  <header class="header">
    <!-- Main Navbar-->
    <nav class="navbar navbar-expand-lg">
      <!-- Search Box -->
      <div class="search-area">
        <div class="search-area-inner d-flex align-items-center justify-content-center">
          <div class="close-btn"><i class="icon-close"></i></div>
          <div class="row d-flex justify-content-center">
            <div class="col-md-8">
              <form action="#">
                <div class="form-group">
                  <input type="search" name="search" id="search" placeholder="検索">
                  <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <!-- Navbar Brand -->
        <div class="navbar-header d-flex align-items-center justify-content-between">
          <!-- Navbar Brand --><a href="{% url 'home:home' %}" class="navbar-brand">Beeeee Blog</a>
          <!-- Toggle Button-->
          <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
        </div>
        <!-- Navbar Menu -->
        <div id="navbarcollapse" class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a href="{% url 'home:home' %}" class="nav-link ">Home</a>
            </li>
            <li class="nav-item"><a href="{% url 'blogs:index' %}" class="nav-link ">Blog</a>
            </li>
            <li class="nav-item"><a href="{% url 'blogs:create' %}" class="nav-link active ">Post</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="main-back bg-original">
    <div class="container">
      <div class="row">
        <main class="post blog-post col-lg-10 offset-lg-1">
          <div class="container frameout">
        {% block body %}{% endblock %}
          </div>
        </main>
      </div>
    </div>
  </div>
  <footer></footer>
  <!-- Javascript files-->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"> </script>
  <script src="{% static 'blogs/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'blogs/vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
  <script src="{% static 'blogs/vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'blogs/js/front.js' %}"></script>
  {% block extra_js %}{% endblock %}
</body>
</html>